sudo: false
language: php

php:
  - 7.1
  - 7.2

env:
  - NETTE_VERSION=":^2.4" COMPOSER_ARGS=""
  - NETTE_VERSION=":^2.4" COMPOSER_ARGS="--prefer-lowest"
  - NETTE_VERSION=":^3.0" COMPOSER_ARGS=""

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer require nette/di${NETTE_VERSION} --no-update
  - travis_retry composer require --dev nette/application${NETTE_VERSION} nette/bootstrap${NETTE_VERSION} latte/latte${NETTE_VERSION} --no-update
  - travis_retry composer update --no-interaction --prefer-source --prefer-stable $COMPOSER_ARGS
  - travis_retry composer global require "jakub-onderka/php-parallel-lint:^1.0.0" "phpstan/phpstan-shim:^0.10.0"

before_script:
  - $HOME/.composer/vendor/bin/parallel-lint -e php,phpt --exclude vendor .
  - $HOME/.composer/vendor/bin/phpstan.phar analyze --no-progress --no-interaction -l 7 src

script:
  - vendor/bin/tester -c tests/php.unix.ini tests

cache:
  directories:
    - $HOME/.composer/cache
